-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Harjoitustyö CASCADE;
DROP TABLE IF EXISTS Opettaja CASCADE;
DROP TABLE IF EXISTS Opiskelija CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
