-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS Assignment CASCADE;
DROP TABLE IF EXISTS Teacher CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Subject CASCADE;
